### ISSUE TITLE
Machines on pullies disappear on server shutdown and restart.

### ISSUE THREAD

**Issue by tgraczyk** [simibubi/Above-and-Beyond#130]
I used a pulley to bring andesite from bedrock up to the surfaces and every once in a while... the machine vanishes into bedrock. 
I've included an image of the end result.
![image](https://user-images.githubusercontent.com/55818178/141697114-ed825320-37d6-4f43-a427-a81be79b5d6b.png)
![image](https://user-images.githubusercontent.com/55818178/141697158-ea636200-6a11-45ba-a0df-8ae6b47145df.png)

And here is an image of how it is usually set up.
![image](https://user-images.githubusercontent.com/55818178/141697243-95a0e9cc-c12c-499b-b9cb-c55296b9a956.png)

Some notes:
This is on a server that I run locally.
I always use /save-all and /stop to shut down the server
This happens after restarting the server and only some of the time.

**Comment by GE0NE** [comment]
Possibly related to [Issue 84 on the Create issues page](https://github.com/Creators-of-Create/Create/issues/84)?

**Comment by GE0NE** [comment]
This issue can be reproduced (albiet inconsistently) when the pulley's chunk is unloaded too, not exclusively on server restart.

**Comment by VeryGoodDev** [comment]
+1 been seeing this issue as well. I haven't done any extensive testing but as far as I can tell it seems to be happening when I move out of render distance of the chunk it's in, despite me force-loading the chunk through the FTB Chunks mod. The solution I'm going to try is replacing the pulley system with a gantry, since I have a gantry-based contraption in the same chunk that has never had this issue, but I am a little sad about it because I love the aesthetic of the pulley-based system. If this gets fixed I'll definitely be going back to the pulley
