### ISSUE TITLE
vacuumulator filter clears instantly

### ISSUE THREAD

**Issue by Thewraith01** [simibubi/Above-and-Beyond#170]
i can put items in the vacuumulator whitelist but as soon as im not in the filter options it wipes my preferences

**Comment by Deadlock989** [comment]
This is a bug/quirk/feature with Thermal rather than this pack.

I found that it won't accept new filters if there is anything in the vacuumulator's inventory.

To set filters reliably, make sure the machine is empty (if it is busy collecting things then turn it off temporarily with the redstone control) before trying to set new filters.
