### ISSUE TITLE
Abnormals Core + CTM Causes Massive Freeze

### ISSUE THREAD

**Issue by BD103** [simibubi/Above-and-Beyond#179]
ConnectedTexturesMod and the Abnormals Core causes mass amounts of errors to be thrown into the log. It eventually fixes itself--which is why nobody's reported it--but it is one of the causes of Minecraft `(not responding)`.

This issue has happened before, but the issue is still not fixed.

- [CTM Issue](https://github.com/Chisel-Team/ConnectedTexturesMod/issues/149)
- [Abnormals Issue](https://github.com/team-abnormals/blueprint/issues/69)
- [Farmer's Delight with same issue](https://github.com/vectorwing/FarmersDelight/issues/169)

Because Chisel requires this mod, I'm not sure how much can be done about it. This may require a decision to remove both CTM and Chisel, or somehow disable the weird recursion that's happening.

**Comment by UnderscoreKilburn** [comment]
I'm not getting this on my end, is anyone still getting this issue?

**Comment by BD103** [comment]
I haven't played Above and Beyond for a while, so I'm not sure. I'll close this for now and open it up if I experience it again.

**Comment by AbiDrew** [comment]
So I've not tried to reproduce this issue, however the bug causing it is still open in CTM. Chasing down all the issues stemming from this bug, it appears that CTM at some point caches and "remembers" that it can't do what it's trying to do and no longer tries, which is why on old instances it eventually stops happening. It's still an active bug though. Not sure what we're going to do to try to address it. Maybe some KubeJS can do something here? IDK. Removing Chisel would be too big a change I think, and Chisel requires CTM. It does seem to require other mods to interact, not just CTM and Abnormals Core. There may be a way, will have to investigate more when I have more time for investigating. @UnderscoreKilburn or you can.

**Comment by BD103** [comment]
You could try making a custom resource pack that disables CTM for the specific blocks that break.

**Comment by UnderscoreKilburn** [comment]
Okay, turns out the issue actually came from Abnormals Core, according to [this](https://github.com/team-abnormals/blueprint/issues/129) the issue has been since fixed, but the fix was never backported to the 1.16 version. That's something we can easily fix on our end though.
