### ISSUE TITLE
Grapple hook with rocket lets you travel 500m/s

### ISSUE THREAD

**Issue by tincopper2** [simibubi/Above-and-Beyond#183]

**Comment by Shuro** [comment]
I don't see the problem. Rockets are not easy to come by.

**Comment by phunfone** [comment]
@Shuro A rocket only costs 1 gunpowder and 1 paper. The problem is that the rocket in the grappling hook does not use durability and has infinite uses, and additionally, the rocket upgrade is not destroyed when crafted with the grappling hook and maxes the grappling hook durability.

**Comment by Shuro** [comment]
@phunfone Dunno what you're playing, but in my C:AAB 1.1 game the crafting recipe for rockets is disabled. I only got rockets via a travelling merchant for some smaragds and since then I use it with the grappling hook, which is a nicer way to travel, a bit more effective than slime sling. 

Slime sling is easily obtainable early on, so I don't see any balancing issues. Grappling Hooks can also be repaired with leather, making it cheap to repair also.

**Comment by phunfone** [comment]
It doesn't show the recipe in JEI (maybe because you can use different amounts of gunpowder to get different flight duration rockets) but I just put a paper and gunpower in a crafting grid.

**Comment by corintho** [comment]
Version 1.2 removed the rocket upgrade altogether:
`Removed the rocket upgrade for grappling hooks`
