### ISSUE TITLE
Random crash at Multiplayer games

### ISSUE THREAD

**Issue by ShenzhenLol** [simibubi/Above-and-Beyond#208]
[crash-2021-11-30_21.47.15-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7629708/crash-2021-11-30_21.47.15-server.txt)
game crashing with no perceptible reason, we didn't start doing create stuff, just getting resources for it

**Comment by BD103** [comment]
It seems that a lot of the mods read as incompatible. Are you running Minecraft 1.16.5? Did you just update to Above and Beyond version 1.2? Did you test this without any extra mods or configuration? 

If you are running the server, definitely remove OptiFine. Try re-installing the modpack. If you aren't, make sure the server is actually modded, not vanilla.

**Comment by gotimo2** [comment]
[crash-2021-11-30_18.19.47-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7633836/crash-2021-11-30_18.19.47-server.txt)

Same issue here. fresh install, no extra mods or configs. reinstalled the modpack, running it with the recommended settings. works fine otherwise, just crashes every so often.

not sure if #209 is the same issue, but it could be

**Comment by BD103** [comment]
I need to test this on my server, I haven’t encountered any of these kind of saplings yet.

**Comment by relaytheory** [comment]
[crash-2021-12-04_12.11.34-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7654316/crash-2021-12-04_12.11.34-server.txt)
[crash-2021-12-04_11.29.11-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7654317/crash-2021-12-04_11.29.11-server.txt)
[crash-2021-12-04_11.30.11-server.txt](https://github.com/simibubi/Above-and-Beyond/files/7654318/crash-2021-12-04_11.30.11-server.txt)

Running a dedicated server through Bisect.
No modifications or config changes made to the modpack, running version 1.2.
This is the last couple crashes encountered today (all within the hour).
Some crash logs were omitted because they've already been posted in other issue reports.

**Comment by oierbravo** [comment]
I thinks is because of forbidden arcanus sappling bug.
See #237
