### ISSUE TITLE
Ender Tanks are broken??

### ISSUE THREAD

**Issue by YorkshirePanda** [simibubi/Above-and-Beyond#259]
![2021-12-20_22 49 03](https://user-images.githubusercontent.com/96449174/146843327-0acaf7f7-3a06-40a5-a2d5-a3a46eb610c5.png)
So just made Ender Tanks in order to have a transfer fluids. Placed the tanks in the world to colour them, and this happened. Also, after making them, the game wouldn't close or save.....

**Comment by maam27** [comment]
I'm going to assume that you have Optifine installed on your client as this is an issue that results from that. Removing optifine from the pack should fix it. If you feel like trying to get it to work normally with Optifine installed then I'd recommend taking a look at the note about Optifine on the packs main page.

**Comment by YorkshirePanda** [comment]
Yeah, i ended up trying that and all is good. Gonna have to try and get it working though, my Potato PC is struggling without Optifine

**Comment by maam27** [comment]
Yea it seems that with enough create items in a space it does become harder to run the pack. Optifine didn't provide as much help as I'd hoped on my end though since it only gained about 10 frames once we had more setup. But you might also benefit from mods like this one: https://www.curseforge.com/minecraft/mc-mods/entity-culling as create is using a lot of block entities.

other than that there is a nice github gist of performance mods for minecraft that you could take a look at to see if there is something that helps for your issues.
https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88#fabric-116
