### ISSUE TITLE
Mechanical Drill

### ISSUE THREAD

**Issue by pennysaver911** [simibubi/Above-and-Beyond#285]
I'm not sure how feasible this would be based on how the drill interacts with everything but for the andesite gen the drill launches whatever it breaks, why is this? Can you make the drill treat it like the block of just broken and then drop normally; also the blocks will warp through solid blocks no matter how many are in it's way.

**Comment by rayanth** [comment]
if the drill is part of a moving contraption, that has an attached storage, it will instead place the drilled-up items in that storage. This is explained in the Ponder for the drill.

You can use a Portable Storage Interface to transfer items from the contraption's storage to a stationary storage elsewhere, otherwise the contraption's storage is inaccessible while it is moving.
