### ISSUE TITLE
CobbleGenRandomizer does not work properly

### ISSUE THREAD

**Issue by jaypitti** [simibubi/Above-and-Beyond#31]
When creating the andesite randomizer, when you break the block it jumps into the lava above it. 

to build it as such

bedrock with water next to it up one block and lava directly 2 blocks above the bedrock

**Comment by simibubi** [comment]
You have a few options here. You could use contraptions with mounted chests to move the drill into the blocks, causing items to be picked up immediately. (See Trailer)
Otherwise, the lava does not strictly have to be above the block, it can flow in from the side just like it would in a cobblestone generator.  

If you need more help, consider clicking the "Feedback and Help" button on the Project Page. Cheers!

**Comment by simibubi** [comment]
sorry about that, I got two issues mixed up- please disregard these changes. Answer above still stands 👍

**Comment by Ciruttai** [comment]
i fixed the problem by having a piston push that block off of the bedrock block before it is broken.
