### ISSUE TITLE
I don't know whats going wrong, I was able to play earlier

### ISSUE THREAD

**Issue by ThePlebber** [simibubi/Above-and-Beyond#314]
[crash-2022-01-13_22.31.33-client.txt](https://github.com/simibubi/Above-and-Beyond/files/7867884/crash-2022-01-13_22.31.33-client.txt)

**Comment by realskudd** [comment]
I'm having a similar issue. I was working on building my crystal to mixer line, mistakenly placed a brass funnel on top of a crafting table, and the game froze. Since then, I haven't been able to get logged back in to play, though my friends are seeing me on the server.

I have tried:

- Updating GPU drivers
- Disabling GPU overclocking
- Enabling GPU overclocking
- Using Oracle Java 8u311
- Disabled Discord overlay
[latest.log](https://github.com/simibubi/Above-and-Beyond/files/7871364/latest.log)

I've included my log file for more specifics.

**Comment by realskudd** [comment]
Actually, I died in game and someone put my stuff in a box then I was able to log in.

**Comment by ThePlebber** [comment]
Hmm I'm not on a server, just a world I created, I was able to load in and play for a bit then hopped off and tried to hop back on later in the day (I use MultiMC) and it just doesn't even load for me, it just keeps crashing. I've tried looking up what to do to fix it and I'm running the right optifine version, minecraft, java, I'm just stuck rn lol

**Comment by realskudd** [comment]
I know this would be very disheartening, but have you tried creating a new single player world?

**Comment by ThePlebber** [comment]
It won't even let me load up the mod, it crashes as soon as I go to load up the mod sadd

**Comment by ThePlebber** [comment]
> I know this would be very disheartening, but have you tried creating a new single player world?

I might have to redownload the modpack🤷‍♂️
