### ISSUE TITLE
Crude oil has no collision

### ISSUE THREAD

**Issue by BlindSE** [simibubi/Above-and-Beyond#34]
Currently, the crude oil found within the wells that spawn across the world has no player collision. The block can still be extracted via bucket or pump but when player touches it,  it behaves like an air block. This caused me (and some other unfortunate souls) to die of fall damage inside the well due to our morbid curiosity.

**Comment by davethwave** [comment]
This is more of a mod issue rather than a pack one. The crude oil just never came with any kind of player collision. Not much the pack author can do from here.

**Comment by simibubi** [comment]
I can make it behave exactly like water, lava or nothing. Such is the sad state of modded fluids in 1.16

**Comment by arslan2012** [comment]
Bump, can we just remove the kubejs crude oil generation entirely?
- It doesn't have a collision but has texture, very confusing in-game.
- Picking up crude oil in an edelwood bucket turns it into a bucket of lava.
- It has no use case in-game, just a replacement for lava to use as fuel.

**Comment by IdrisQe** [comment]
Adding to this, the Thermal Series already has its own Crude Oil, included in the modpack, so I don't understand the purpose of adding another Crude Oil instead of tweaking that one and adding it to the custom structure.

_(Also Forge really needs to get its sh*t together with fluids, it's been messed up since like 1.13 right? It's been two and a half years, cripes.)_
