### ISSUE TITLE
[1.3] Only one Recipe for Andesite Casing

### ISSUE THREAD

**Issue by Anoyomouse** [simibubi/Above-and-Beyond#352]
Playing the pack (version 1.3), I wanted to automate all the way to Andesite Machine, however, there isn't a recipe for Andesite Casing you can easily automate early game.

I haven't tested, but assuming I could potentially use a "crafty turtle" to do the crafting from the box of wood and the box of Andesite Alloy, but not having the ability to easily have a box of Andesite Casings around seems like an oversight.

(Image is of pressing "r" on andesite casing showing only a single recipe, not even a mechanical crafting recipe)
![image](https://user-images.githubusercontent.com/4417100/151754319-cd76c780-3b42-464f-b523-8a7f108c5c0b.png)

**Comment by UnderscoreKilburn** [comment]
This seems to be caused by a recent update to KubeJS that switches it to a custom implementation of vanilla crafting recipes, it looks like Create won't detect any shapeless recipe defined by a KubeJS script (i.e. any recipe specific to the modpack, like nickel compound).

You can still use mechanical crafters though, they should work even if JEI doesn't show a recipe.
