### ISSUE TITLE
Trying to make a server for me and my friends doesn't work

### ISSUE THREAD

**Issue by Mouph** [simibubi/Above-and-Beyond#398]
![image](https://user-images.githubusercontent.com/68927573/156900302-87b2cae8-01eb-43e0-84e1-022a908c66e7.png)

this is the error message it gives no idea if this helps or not

**Comment by BlazeSmith** [comment]
I have found the issue after digging around the forums a little
~~
https://github.com/simibubi/Above-and-Beyond/issues/359#issuecomment-1030290228
~~
Java 321, the latest java, is incompatible with the current version of forge. to run a server, you need to downgrade to an older version of java (such as 312). This issue is technically resolved but if anyone has a more permanent answer than downgrading java please let me know!

**Comment by Mouph** [comment]
@BlazeSmith Thank you i could kiss you on the mouth oh my god

**Comment by BraveCaperCat** [comment]
Help me with #396
