### ISSUE TITLE
Unexplained high MSPT 不明原因的卡顿

### ISSUE THREAD

**Issue by zzx517** [simibubi/Above-and-Beyond#430]
如题。即使是新建的超平坦也卡。v1.
![2022-05-06_16 04 37](https://user-images.githubusercontent.com/105040779/167093926-6cf28c14-5705-4ce8-a243-84042e2778bf.png)
3

**Comment by zzx517** [comment]
version 1.3

**Comment by TimJElliott** [comment]
Hi, I have this same issue as well for the last month or so.  Happens on fresh worlds and even a different PC altogether.  Very frustrating. Also 1.3

**Comment by AbiDrew** [comment]
Are you guys playing Single-player only, or have either of you tried to replicate this behavior on a server?

**Comment by zzx517** [comment]
I play single-player only.

**Comment by new-3** [comment]
the mod 'straw golems' is causing this. Golems are so cute but they are two-faced. If you open data folder of your world, you'll see "strawgolem.dat" that have exceedingly big size compared to other files. Just remove the mod and you'll be fine.

**Comment by AbiDrew** [comment]
Ah, thank you for the troubleshooting work @new-3. Now we know where to investigate for a solution and to reproduce the issue.

**Comment by TimJElliott** [comment]
Deleting the Straw Golems mod seems to have worked!  Does anybody know if that is used in the pack's progression at all?

**Comment by new-3** [comment]
@AbiDrew [this](https://spark.lucko.me/wdWhKJ28Qb) is my spark report right before the problem went so big. hope it helps

@TimJElliott They basically farm crops so there are plenty alternatives, I think you don't worry about that.

**Comment by AbiDrew** [comment]
@new-3 that's exactly what we needed to see. There's a completely uncalled for amount of tick time being used here, and particularly by java.util.PriorityQueue.siftDownComparable() function at 58.23% and it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap.get() function at 21.29%

Saved us some time finding this ourselves, we have something here to show upstream if it hasn't already been fixed by the Straw Golem mod dev.

**Comment by zzx517** [comment]
The problem has been solved. Thank you very much.
