### ISSUE TITLE
mod doesn't download

### ISSUE THREAD

**Issue by skyethay** [simibubi/Above-and-Beyond#432]
I'm using the app curse forge to download the modpack but when I try to download it says:

this modpack requires a dependency that is missing or no longer available. missing id:511276

is there something I can do to fix it?

**Comment by Pheubel** [comment]
Right now curse forge is down and it has been for a while, it has prevented me from installing the mod pack in general. So maybe if you try again later when their server issue has been resolved it (probably) will work.

**Comment by AbiDrew** [comment]
As Pheubel said, this is an issue with Curseforge. To elaborate a bit further, Curseforge has been having sporadic problems ever since Overwolf bought it from Amazon, who bought Twitch but didn't want to keep Curseforge. The only real option is to retry at different times until it eventually works at some point. As far as I am aware, as of this moment, things should be working normally. But there's no real guarantee.
