### ISSUE TITLE
Supplementaries Flax crops not growing normally

### ISSUE THREAD

**Issue by Konin-Sensei** [simibubi/Above-and-Beyond#454]
![image](https://user-images.githubusercontent.com/38869772/175425842-ce396c70-63c7-4daa-955e-6b16243941e7.png)
Pictured above, the flax from the mod supplementaries is initially growing fine but turns into this mess with some crops only having their upper half actually in the world. I've tried reconnecting to my server and restarting it as well. 
I initially thought it could be a rendering issue as I've installed optifine but the bottom half of the crops is actually missing, I can stomp out the tilled dirt beneath without the top half decaying and can place blocks into the space where the bottom half of the crop should be. 
While the crops are behaving like this, the harvesters will only collect seeds and no flax.
Also dropped this issue in the supplementaries repository as im not sure if this is a problem with the mod or the pack [linked here](https://github.com/MehVahdJukaar/Supplementaries/issues/256)

**Comment by Konin-Sensei** [comment]
@AbiDrew Duplicate to what issue? the only other issue I saw mentioning flax was one where the right-click harvest was not working

**Comment by AbiDrew** [comment]
Oh, you're right. I misread it.

**Comment by Konin-Sensei** [comment]
Looks like this has more to do with the harvester upon some testing the supplementaries dev asked me to try. I still don't see another issue for this though so I don't think this is a duplicate. [short clip of the issue uploaded to youtube](https://youtu.be/4UmFb26pBY0)

**Comment by AbiDrew** [comment]
Could you look for this issue on https://github.com/Creators-of-Create/Create please? This looks to be an issue with the Mechanical Harvester from upstream Create. It may already be fixed for 1.18.2 and the fix just never got back-ported to 1.16.5. If you can't find it there, create an issue for it there and be sure to let them know you're using the version of the mod that's in the Create Above and Beyond pack. Just be sure to look carefully first, if it was already closed for 1.18.2 and never back-ported then there's no reason to make another issue for it just because the issue remains present in 1.16.5.

**Comment by Konin-Sensei** [comment]
Doesn't look like there's an issue for it on create however it does also seem that just harvesting the crop from the bottom block rather than the second works totally fine so it may just be because the flax grows two tall but harvests down to the soil rather than just the top half like sugar cane. so while it is sort of an issue, I should have been harvesting the bottom block anyways apparently. Going to close this since it's not really breaking anything.
