### ISSUE TITLE
vannila spawner after changing converts back to its type after first spawn

### ISSUE THREAD

**Issue by minecrafterseppe** [simibubi/Above-and-Beyond#53]
grabbed a cave spider spawner in a cart  
placed it down changed it to wither skeleton spawner
picked it up 
placed it again 
it spawned once
and converted back into cave spider spawner
version 1.1 of the modpack

seems to be a comeback of this issue
https://github.com/Creators-of-Create/Create/issues/1401

**Comment by minecrafterseppe** [comment]
update it seems to happen regardlef of being picked up
cheating in a spawner and changing it   works just fine

**Comment by klugemonkey** [comment]
Still seems to be an issue in 1.2.  Using blaze spawn egg on spawner, changes that spawner's next entity spawned  (spawn data), but then it reverts.  Should be changing the spawn potentials.   This happens for some spawn eggs.  Others when applied to a spawner will change it permanently, but retain the previous settings for custom spawners like loot and lighting level, which seems quite odd (ie. magma cube dropping a golden helmet and rusty pickaxe instead of magma cream and only spawning small sizes).  Changing a spawner should probably reset it's characteristics to the norms for that mob.

**Comment by lukaspkrr** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/162 might have some insight.
